meta:
  engine: 4.1.0
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 3
  py: ky + 3
points:
  zones:
    matrix:
      anchor:
        shift: [50, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          rows.top.skip: true
          key.column_net: P0
        pinky:
          key.column_net: P1
        ring:
          key:
            column_net: P2
            stagger: 3
        middle:
          key.column_net: P3
        index:
          key.column_net: P4
        inner:
          key.column_net: P5
      rows:
        bottom:
          row_net: P6
        home:
          row_net: P7
        top:
          row_net: P8
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx, -ky - 2]
      columns:
        inner:
          key:
            shift : [-7, 0]
            column_net: P5
        middle:
          key:
            shift: [-4.5, -2]
            splay: -10
            column_net: P4
        outer:
          key:
            width: 1.5kx
            splay: 80
            shift: [0, 2]
            column_net: P3

      rows:
        extra:
          row_net: P9

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
      fillet: 2
  cutout:
    - what: rectangle
      where: true
      size: [14,14]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_outer_extra
          shift: [0.75px,-0.5py]
        # - ref: thumb_outer_extra
        #   shift: [0.75px,0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px + 0.95px,0]
        - ref: matrix_inner_top
          shift: [0.5px + 0.95px,0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px,kx + 0.5py + 3]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
        - ref: thumb_inner_extra
          shift: [-0.5px,0.5py - 4]
        - ref: thumb_inner_extra
          shift: [-0.5px,-0.5py]  
        - ref: thumb_outer_extra
          shift: [-0.75px,-0.5py]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: cutout


pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      keyswitches:
        where: true
        what: choc
        params:
          keycaps: true
          hotswap: true
          reverse: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
        adjust:
          shift: [0, -5]
      mcu:
        what: mcu_nice_nano
        where:
          ref: matrix_inner_top
          shift: [0.95px, -7]
          rotate: 0
        params:
          reversible: true
      knob:
        what: sparkfun_rotary_encoder
        where:
          ref: matrix_outer_home
          shift: [-2.5, 1px + 2]
          rotate: 0
        params:
          A: P21
          B: GND
          C: P20
          S1: P19
          reversible: true
      reset:
        what: reset_switch_tht_top
        params:
          from: GND
          to: RST
          reversible: true
        where:
          ref: matrix_inner_bottom
          shift: [1.3px, 3]
          rotate: -90

      oled:
        what: display_ssd1306
        params:
          reversible: true
          SDA: P10
          SCL: P16
        where:
          ref: matrix_inner_home 
          shift: [0.95px, 6]
      power_switch:
        what: power_switch
        where:
          ref: matrix_inner_bottom
          shift: [1.35px, -6.5]
          rotate: 0
        params:
          from: BAT+
          to: VCC
          reversible: true
      holeTopLeft:
        what: mounting_hole_plated
        where:
          - ref: matrix_outer_home
            shift: [-0.4kx, 0.65ky]
      holeBottomLeft:
        what: mounting_hole_plated
        where:
          - ref: matrix_middle_bottom
            shift: [-0.5kx, -0.6ky]
      holeTopRight:
        what: mounting_hole_plated
        where:
          - ref: matrix_inner_top
            shift: [0.5kx, 0]
      holeBottomRight:
        what: mounting_hole_plated
        where:
          - ref: thumb_outer_extra
            shift: [-0.7kx, 0]



cases:
  plate:
    - name: combo
      extrude: 1.2
